import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { FormEvent, useEffect, useState } from 'react'
import { io } from 'socket.io-client'
import { useRouter } from 'next/router'
import { Duck, DuckMessage } from '@/types'
import DuckImage from '../components/duckImage'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
    
  const roomId = router.query.id as string
  const [messages,setMessages] = useState<DuckMessage[]>([])
  const [duckColor,setDuckColor] = useState<string>('#e9ff70')
  const [duckName,setDuckName] = useState<string>('Duck')
  const [roomDucks,setRoomDucks] = useState<any[]>([])
 

  const socketIoServer = process.env.NODE_ENV == 'development' ? 'http://localhost:3000' : 'https://socket-io-quackrooms-server-142859f50720.herokuapp.com/'
  const socket = io(socketIoServer)



  useEffect(()=>{

    if(!router.isReady){
      return
    }

    socket.connect()
    socket.emit('joinRoom', roomId,duckName,duckColor);
    
    socket.on(`new message`,(msg:DuckMessage)=>{
      console.log(msg)
      setMessages((prevMessages) => [...prevMessages, msg]);
    })

    socket.on(`Users in room`,(users)=>{
      console.log(users)
      setRoomDucks(users)
    })

    socket.on(`changeDuck:`,(duck)=>{
     console.log('A duck changed color or name')
    })


    socket.on('New duck in the room',(ducks)=>{

    })

     // Clean up the socket connection when the component unmounts
     return () => {
      socket.disconnect();
    };

  },[router])


  const serverChangeDuckColor=async (roomCode:string,duckColor:string,duckNumber:number) => {
    socket.emit('changeDuck')
  }  

  const sendMessage = async (event:FormEvent) => {
    event.preventDefault()
    const message = (document.getElementById('input') as HTMLInputElement).value 
    
    const messageObj:DuckMessage = {
      text: message,
      sender:duckName,
      roomId:roomId
    }

    socket.emit('message', messageObj);
    (document.getElementById('input') as HTMLInputElement).value = '' 

  }

function DuckListItem(props:Duck){
  return(
    <div className={styles.duckListItem}>
        <div className={styles.duckIcon}>
            <DuckImage color={duckColor} duckName={''}/>
        </div>
        <div className={styles.duckInfo}>
          <h4>Duck name</h4>
        </div>
      </div>
  )
}

  return (
<>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main>
     <div className={styles.duckEditorContainer}>
      <div className={styles.duckImageContainer}>
        <DuckImage color={duckColor} duckName={''}/>
      </div>
      <div className={styles.duckEditor}>
      <h3>Your Duck</h3>
        <label htmlFor="duckColor">Duck color </label>
        <input type="color" id="duckColor" onChange={(e)=>setDuckColor(e.target.value)} onBlur={()=>serverChangeDuckColor(roomId,duckColor,0)} defaultValue={duckColor}></input>
        <label htmlFor="duckName">Duck Name: </label>
        <input type="text" id="duckName" onBlur={(e)=>setDuckName(e.target.value)} defaultValue={'Duck'}></input>
      </div>
     </div>
     <div className={styles.duckList}>
     <h3>Online Ducks</h3>
      <p>{JSON.stringify(roomDucks)}</p>
     </div>
     <ul id="messages">
      {messages.map((message,index)=>{
        return (
          <li key={index}>{message.sender}: {message.text}</li>
        )
      })}
     </ul>
      <form id="form" action="" onSubmit={(e)=>sendMessage(e)}>
        <input id="input" autoComplete="off" /><button type='submit'>Send</button>
      </form>
     </main>
    </>
  )
}
